# Generated by Django 2.0.3 on 2018-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('game_name', models.CharField(max_length=20)),
                ('game_link', models.CharField(max_length=100)),
                ('game_title', models.CharField(max_length=100)),
                ('game_picture', models.CharField(max_length=300)),
                ('game_nickname', models.CharField(max_length=100)),
                ('game_time', models.FloatField()),
                ('game_count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='laterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_link', models.CharField(max_length=100)),
                ('movie_pic', models.CharField(max_length=100)),
                ('movie_time', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=50)),
                ('movie_region', models.CharField(max_length=20)),
                ('movie_people', models.IntegerField()),
                ('movie_preview', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lsjt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=15)),
                ('month', models.CharField(max_length=15)),
                ('day', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_link', models.CharField(max_length=100)),
                ('movie_actor', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=20)),
                ('movie_director', models.CharField(max_length=50)),
                ('movie_time', models.CharField(max_length=20)),
                ('movie_region', models.CharField(max_length=50)),
                ('movie_release', models.CharField(max_length=10)),
                ('movie_score', models.FloatField()),
                ('movie_pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='moviesuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_link', models.CharField(max_length=100)),
                ('movie_score', models.FloatField()),
                ('movie_pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mtbpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('picurl', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='mtbziliao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('uname', models.CharField(max_length=20)),
                ('shengao', models.CharField(max_length=5)),
                ('zhongliang', models.CharField(max_length=5)),
                ('xiongwei', models.CharField(max_length=5)),
                ('yaowei', models.CharField(max_length=5)),
                ('tunwei', models.CharField(max_length=5)),
                ('xiema', models.CharField(max_length=5)),
                ('fase', models.CharField(max_length=10)),
                ('yanjing', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='musiclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('cata', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='qiubai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shicilist',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('cata', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='technews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('tag', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('img', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='tvlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_name', models.CharField(max_length=100)),
                ('tv_link', models.CharField(max_length=100)),
                ('tv_score', models.FloatField()),
                ('tv_pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='yaoyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('date', models.DateTimeField()),
                ('cata', models.CharField(blank=True, max_length=20)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='zmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=12)),
                ('picurl', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
